backend:
  name: github
  repo: danielLublinsky/ram-physiotherapy # ← CHANGE THIS to match your GitHub repo
  branch: main # or 'master', depending on your default branch

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "text_files"
    label: "Text Pages"
    folder: "txt"
    create: true
    slug: "{{slug}}"
    extension: "txt"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
